import { useEffect, useState } from 'react'
import { Cpu, Globe, Pencil, RefreshCw, ShieldCheck, Trash2 } from 'lucide-react'
import { CURRENCIES } from '@shared/finance'
import Panel from './Panel'
import Disclaimer from './Disclaimer'
import { getHealth } from '../services/api'

interface Props {
  currency: string
  mode: 'ai' | 'demo'
  onCurrency: (c: string) => void
  onEdit: () => void
  onReset: () => void
}

export default function SettingsPanel({ currency, mode, onCurrency, onEdit, onReset }: Props) {
  const [health, setHealth] = useState<Awaited<ReturnType<typeof getHealth>> | 'loading'>('loading')
  const check = () => {
    setHealth('loading')
    getHealth().then(setHealth)
  }
  useEffect(check, [])

  return (
    <div className="grid gap-6 lg:grid-cols-2">
      <Panel title="AI connection" subtitle="How FinWise AI generates your advice" icon={Cpu}>
        <dl className="space-y-3 text-sm">
          <div className="flex justify-between">
            <dt className="text-slate-500">Current plan generated by</dt>
            <dd className="font-semibold">{mode === 'ai' ? 'Google Gemini' : 'Demo Mode engine'}</dd>
          </div>
          <div className="flex justify-between">
            <dt className="text-slate-500">Backend</dt>
            <dd className="font-semibold">
              {health === 'loading' ? 'Checking…' : health ? (health.backend === 'flask' ? 'Flask API' : 'Serverless API') : 'Not reachable (local fallback)'}
            </dd>
          </div>
          <div className="flex justify-between">
            <dt className="text-slate-500">Gemini API key</dt>
            <dd className={`font-semibold ${health !== 'loading' && health?.ai_configured ? 'text-emerald-600' : 'text-amber-600'}`}>
              {health === 'loading' ? '…' : health?.ai_configured ? `Configured · ${health.model}` : 'Not configured'}
            </dd>
          </div>
        </dl>
        <p className="mt-4 rounded-xl bg-slate-50 p-3 text-xs leading-relaxed text-slate-600">
          The Gemini API key is stored only in the backend environment (<code className="font-mono">GEMINI_API_KEY</code>) and is never sent to your browser. Without a key,
          FinWise AI runs in Demo Mode with realistic rule-based insights.
        </p>
        <button onClick={check} className="btn-secondary mt-4 py-2">
          <RefreshCw className="h-4 w-4" /> Re-check connection
        </button>
      </Panel>

      <Panel title="Preferences" icon={Globe}>
        <label htmlFor="cur" className="label">
          Display currency
        </label>
        <select id="cur" value={currency} onChange={(e) => onCurrency(e.target.value)} className="input">
          {CURRENCIES.map((c) => (
            <option key={c.code} value={c.code}>
              {c.code} ({c.symbol})
            </option>
          ))}
        </select>
        <p className="mt-1.5 text-xs text-slate-500">Changes the symbol and formatting only — amounts are not converted.</p>
        <div className="mt-6 flex flex-wrap gap-3">
          <button onClick={onEdit} className="btn-secondary py-2">
            <Pencil className="h-4 w-4" /> Edit my inputs
          </button>
          <button onClick={onReset} className="inline-flex items-center gap-2 rounded-xl border border-rose-200 px-4 py-2 text-sm font-semibold text-rose-600 transition hover:bg-rose-50">
            <Trash2 className="h-4 w-4" /> Clear my data
          </button>
        </div>
      </Panel>

      <Panel title="Privacy" icon={ShieldCheck} className="lg:col-span-2">
        <ul className="grid gap-3 text-sm text-slate-600 sm:grid-cols-3">
          <li>Your financial data is kept only in this browser tab and disappears when you close or clear it.</li>
          <li>Requests are processed in memory to generate advice and are never saved to a database.</li>
          <li>Inputs are validated and sanitised on the server before being sent to Gemini.</li>
        </ul>
        <div className="mt-5">
          <Disclaimer />
        </div>
      </Panel>
    </div>
  )
}
