import { useMemo } from 'react'
import { ArrowRight, BarChart3, Bot, Info, Pencil, PieChart as PieIcon, PiggyBank, Sparkles, Waves, Wallet } from 'lucide-react'
import { computeMetrics, formatMoney, type ChatMessage, type FinancialInput } from '@shared/finance'
import type { AdviceResult } from '../services/api'
import Sidebar, { NAV } from '../components/Sidebar'
import Logo from '../components/Logo'
import Panel, { AiBadge } from '../components/Panel'
import SummaryCards from '../components/SummaryCards'
import BudgetPlan from '../components/BudgetPlan'
import GoalProgress from '../components/GoalProgress'
import SavingSuggestions from '../components/SavingSuggestions'
import MonthlySummary from '../components/MonthlySummary'
import WhatIf from '../components/WhatIf'
import AskAI from '../components/AskAI'
import SettingsPanel from '../components/SettingsPanel'
import Disclaimer from '../components/Disclaimer'
import DonutChart from '../charts/DonutChart'
import IncomeExpenseChart from '../charts/IncomeExpenseChart'
import CashFlowChart from '../charts/CashFlowChart'
import { CATEGORY_COLORS } from '../charts/theme'

export type Tab = 'dashboard' | 'budget' | 'savings' | 'advisor' | 'settings'

interface Props {
  input: FinancialInput
  advice: AdviceResult
  tab: Tab
  onTab: (t: Tab) => void
  chat: ChatMessage[]
  onChat: (m: ChatMessage[]) => void
  onEdit: () => void
  onReset: () => void
  onCurrency: (c: string) => void
}

const TITLES: Record<Tab, { title: string; sub: string }> = {
  dashboard: { title: 'Financial Dashboard', sub: 'Your month at a glance' },
  budget: { title: 'Budget', sub: 'Your AI-generated budget plan and cash flow' },
  savings: { title: 'Savings', sub: 'Personalised saving ideas and what-if scenarios' },
  advisor: { title: 'AI Advisor', sub: 'Ask questions and get insights about your finances' },
  settings: { title: 'Settings', sub: 'Preferences, AI connection and privacy' },
}

export default function Dashboard({ input, advice, tab, onTab, chat, onChat, onEdit, onReset, onCurrency }: Props) {
  const m = useMemo(() => computeMetrics(input), [input])
  // Use the AI's recommendation when valid, but never more than what is actually available.
  const savings = Math.max(0, Math.min(Math.max(0, m.available), advice.budget_plan.recommended_savings || m.recommendedSavings))
  const money = (v: number) => formatMoney(v, input.currency)
  const axis = (v: number) => formatMoney(v, input.currency, true)
  const go = (t: Tab) => {
    onTab(t)
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }

  const categories = input.expenses
    .filter((e) => e.amount > 0)
    .sort((a, b) => b.amount - a.amount)
    .map((e, i) => ({ name: e.name, value: e.amount, color: CATEGORY_COLORS[i % CATEGORY_COLORS.length] }))

  const { title, sub } = TITLES[tab]
  const currentIndex = NAV.findIndex((n) => n.id === tab)
  const next = tab !== 'settings' && tab !== 'advisor' ? NAV[currentIndex + 1] : null

  return (
    <div className="min-h-screen">
      <Sidebar tab={tab} onTab={go} mode={advice.mode} goal={input.financialGoal} progress={m.goalProgress} />

      <div className="pb-24 lg:pb-10 lg:pl-64">
        {/* Mobile top bar */}
        <div className="sticky top-0 z-20 flex h-14 items-center justify-between border-b border-slate-200/70 bg-white/90 px-4 backdrop-blur lg:hidden">
          <Logo />
          <button onClick={onEdit} className="flex items-center gap-1.5 rounded-lg px-2.5 py-1.5 text-sm font-semibold text-slate-600 hover:bg-slate-100">
            <Pencil className="h-4 w-4" /> Edit
          </button>
        </div>

        <main className="mx-auto max-w-7xl space-y-6 px-4 py-6 sm:px-6 lg:px-10 lg:py-9">
          <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
            <div>
              <p className="flex items-center gap-2 text-sm font-medium text-slate-500">
                <Sparkles className="h-4 w-4 text-brand-500" /> {sub}
              </p>
              <h1 className="mt-1 text-2xl font-bold tracking-tight sm:text-3xl">{title}</h1>
            </div>
            <div className="flex items-center gap-2">
              <AiBadge mode={advice.mode} />
              <button onClick={onEdit} className="btn-secondary hidden py-2 lg:inline-flex">
                <Pencil className="h-4 w-4" /> Edit inputs
              </button>
            </div>
          </header>

          {(advice.notice || advice.mode === 'demo') && tab !== 'settings' && (
            <div className="flex items-start gap-3 rounded-2xl border border-brand-100 bg-brand-50/60 px-4 py-3 text-sm text-brand-900">
              <Info className="mt-0.5 h-4 w-4 shrink-0 text-brand-600" />
              <p>
                <span className="font-semibold">{advice.notice ?? 'Demo Mode is on.'}</span>{' '}
                Insights are generated by FinWise AI’s built-in engine from your numbers. Add a <code className="font-mono text-xs">GEMINI_API_KEY</code> to the backend for live
                Gemini analysis.
              </p>
            </div>
          )}

          {tab === 'dashboard' && (
            <>
              <SummaryCards m={m} savings={savings} money={money} />
              <div className="grid gap-6 xl:grid-cols-2">
                <Panel title="Income vs Expenses" subtitle="Where your monthly income goes" icon={BarChart3}>
                  <IncomeExpenseChart income={m.totalIncome} needs={m.needsTotal} wants={m.wantsTotal} format={money} formatAxis={axis} />
                </Panel>
                <Panel title="Expense breakdown" subtitle={`${categories.length} categories this month`} icon={PieIcon}>
                  <DonutChart data={categories} format={money} centerLabel="Spent" centerValue={money(m.totalExpenses)} />
                </Panel>
              </div>
              <div className="grid gap-6 xl:grid-cols-[1.5fr_1fr]">
                <MonthlySummary advice={advice} />
                <div className="space-y-6">
                  <GoalProgress input={input} m={m} savings={savings} money={money} />
                  <InsightsCard insights={advice.insights} onAsk={() => go('advisor')} />
                </div>
              </div>
              <SavingSuggestions advice={advice} money={money} limit={3} onMore={() => go('savings')} />
            </>
          )}

          {tab === 'budget' && (
            <>
              <BudgetPlan input={input} m={m} advice={advice} savings={savings} money={money} />
              <div className="grid gap-6 xl:grid-cols-[1.5fr_1fr]">
                <Panel title="Monthly cash flow" subtitle="How income flows through needs, wants and savings" icon={Waves}>
                  <CashFlowChart income={m.totalIncome} needs={m.needsTotal} wants={m.wantsTotal} savings={savings} format={money} formatAxis={axis} />
                </Panel>
                <GoalProgress input={input} m={m} savings={savings} money={money} />
              </div>
            </>
          )}

          {tab === 'savings' && (
            <>
              <SavingSuggestions advice={advice} money={money} />
              <WhatIf key={`${m.totalIncome}-${m.totalExpenses}-${savings}`} input={input} m={m} savings={savings} money={money} axis={axis} />
            </>
          )}

          {tab === 'advisor' && (
            <div className="grid gap-6 xl:grid-cols-[1.6fr_1fr]">
              <AskAI input={input} messages={chat} onMessages={onChat} />
              <div className="space-y-6">
                <InsightsCard insights={advice.insights} />
                <Panel title="Your snapshot" subtitle="Context FinWise AI uses to answer" icon={Wallet}>
                  <dl className="space-y-2.5 text-sm">
                    {[
                      ['Monthly income', money(m.totalIncome)],
                      ['Total expenses', money(m.totalExpenses)],
                      ['Available balance', money(m.available)],
                      ['Suggested savings', money(savings)],
                      ['Goal', `${input.financialGoal} · ${money(input.targetAmount)}`],
                      ['Risk preference', input.riskPreference],
                    ].map(([k, v]) => (
                      <div key={k} className="flex justify-between gap-4">
                        <dt className="text-slate-500">{k}</dt>
                        <dd className="tabular text-right font-semibold capitalize">{v}</dd>
                      </div>
                    ))}
                  </dl>
                </Panel>
              </div>
            </div>
          )}

          {tab === 'settings' && <SettingsPanel currency={input.currency} mode={advice.mode} onCurrency={onCurrency} onEdit={onEdit} onReset={onReset} />}

          {next && (
            <button
              onClick={() => go(next.id)}
              className="group flex w-full items-center justify-between rounded-2xl border border-slate-200 bg-white px-5 py-4 text-left transition hover:border-brand-300 hover:shadow-card"
            >
              <span className="flex items-center gap-3">
                <next.icon className="h-5 w-5 text-brand-600" />
                <span>
                  <span className="block text-xs text-slate-500">Next</span>
                  <span className="font-semibold">
                    {next.id === 'budget' ? 'See your AI budget plan' : next.id === 'savings' ? 'Saving suggestions & What-If simulator' : 'Ask FinWise AI'}
                  </span>
                </span>
              </span>
              <ArrowRight className="h-5 w-5 text-slate-400 transition group-hover:translate-x-1 group-hover:text-brand-600" />
            </button>
          )}

          <Disclaimer compact />
        </main>
      </div>
    </div>
  )
}

function InsightsCard({ insights, onAsk }: { insights: string[]; onAsk?: () => void }) {
  return (
    <Panel title="AI Insights" icon={PiggyBank}>
      <ul className="space-y-3">
        {insights.map((t) => (
          <li key={t} className="flex gap-3 text-sm leading-relaxed text-slate-700">
            <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-brand-500" /> {t}
          </li>
        ))}
      </ul>
      {onAsk && (
        <button onClick={onAsk} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-brand-50 py-2.5 text-sm font-semibold text-brand-700 transition hover:bg-brand-100">
          <Bot className="h-4 w-4" /> Ask FinWise AI a question
        </button>
      )}
    </Panel>
  )
}
